### ISSUE TITLE
is there a way to monitor the Queue size in the socket channel, especially for the one used for passing minibatches?

### ISSUE THREAD

**Issue by yaoli** [mila-udem/platoon#49]
googled a bit, but couldn't find anything useful?

**Comment by bartvm** [comment]
The way it's currently implemented, there is no way: http://zeromq.org/area:faq#toc8

> **How do I determine how many messages are in queue?**
> This isn't possible. At any given time a message may be in the ZeroMQ sender queue, the sender's kernel buffer, on the wire, in the receiver's kernel buffer or in the receiver's ZeroMQ receiver queue. Furthermore, a ZeroMQ socket can bind and/or connect to many peers. Each peer may have different performance characteristics and therefore a different queue depth. Any "queue depth" number is almost certainly wrong, so rather than provide incorrect information the library avoids providing any view into this data.

**Comment by yaoli** [comment]
hmm, bummer! But thanks Bart.

**Comment by mgermain** [comment]
Yeah we definitely need to take look at other options like nanomsg for the queue.

**Comment by bartvm** [comment]
This doesn't have much to do with ZeroMQ vs. nanomsg though, it's more between using a broker or not. Since we don't use a broker, there's no middleman that keeps track of incoming and outgoing packets, and everything is simply queued at the sockets. This happens on a very low level, so there's no easy way to monitor stuff, but the advantage is speed and simplicity.

If you want to do monitoring, you'd need to look at using a message broker like RabbitMQ. Although RabbitMQ is generally used with AMQP, it should play nice with ZeroMQ as well.

**Comment by bartvm** [comment]
See e.g. https://www.rabbitmq.com/tutorials/tutorial-two-python.html

**Comment by mgermain** [comment]
Yeah, I was not clear at all.
What you said is true, but what I had in mind is that I think that using another message queue is probably worth considering at this point. Brokerless or not.

**Comment by mgermain** [comment]
The comparison to ZeroMQ in the [nanomsg](http://nanomsg.org/documentation-zeromq.html) documentation is pretty interesting, especially the Threading Model section.

Also, I just stumbled upon this [blog post](http://bravenewgeek.com/dissecting-message-queues/) comparing multiple options.

**Comment by yaoli** [comment]
Basically, my original intention is to be able to tune a good queue max
size. Otherwise, I don't really see any other use for getting the size of
the queue, hence probably not worth the effort.
