### ISSUE TITLE
Question regarding custom parameter update rule

### ISSUE THREAD

**Issue by rparrapy** [mila-udem/platoon#64]
I have a (probably noob-level) question regarding how ASGD is implemented in Platoon, which I need to understand in order to customized for my needs. If this is not the right place to ask this kind of questions, please let me know. Current implementation is as follows:

```python
class ASGD(ParamSyncRule):
    def theano_update(self, local_params):
        import theano

        local_vals = [p.get_value(borrow=True, return_internal_type=True)
                      for p in local_params]
        master_inps = [l.type() for l in local_params]
        self.old_locals = [theano.shared(l) for l in local_vals]
        # This updates the global params with the difference between
        # old and current (aka the gradients).
        ret = [m + (p - o) for (m, p, o) in zip(master_inps, local_params,
                                                self.old_locals)]
        # This keeps values before the update for the local params
        ups = list(zip(self.old_locals, ret))
        # This updates the local params to be the same as the global
        ups += list(zip(local_params, ret))
        return theano.function(master_inps, ret, updates=ups)
```

How do shared variables `local_params` and `self.old_locals` have different values assigned? We create `self.old_locals` from the values of `local_params`, so aren't they supposed to be equal? Or is it related to the keyword arguments used (borrow=True, return_internal_type=True)? Am I missing something?

Shouldn't the implementation just add the difference between local and master to master params (as it is done for EASGD)?

My end goal is to have a shared variable (let's say `local_params[-1]`) that is **not**  a model parameter, and hence it should be updated simply as I described above. That is, replace the old value with the new value. Do you have any suggestions on how to achieve this? My naive attempt was the following code:

```python
        ret = [m + (p - o) for (m, p, o) in zip(master_inps[:-1], local_params[:-1],
                                                self.old_locals[:-1])]
        ret.append(local_params[-1])
```
However, `local_params[-1]` is not updated with this change. Any hint would be appreciated :)

**Comment by mgermain** [comment]
This might be a bit convoluted but I'll try to keep it short.
For the first part of your question, as you can see [here](https://github.com/mila-udem/platoon/blob/master/platoon/channel.py#L315) at init time self.old_locals is set to the initial values of the parameters.
Then when the function returned by the `theano_update` of the ASGD class is called [here](https://github.com/mila-udem/platoon/blob/master/platoon/channel.py#L435) the sum of the updates since the previous sync are [applied to the master params](https://github.com/mila-udem/platoon/blob/master/platoon/param_sync.py#L20) and the local_params and old_locals are updated to the same value.

So yes EASGD and ASGD works differently and I'm not exactly sure what your end goal is. This might be adressed bu using plain communication between the workers and the controler `worker.send_req({"update_some_val": 5})`.

**Comment by rparrapy** [comment]
Thanks for your answer, I think I was just confused about how Theano function definition works. My end goal is to implement a scenario where some workers do not do SGD, but compute some other task to inform batch selection in SGD worker(s). I am currently working on trying to parallelize [this approach](http://arxiv.org/pdf/1511.06343v3.pdf) approach, in a manner similar to what is proposed in figure 1 [here](http://arxiv.org/pdf/1511.06481v6.pdf).

Hence, I need a loss-by-sample-index array as a shared variable too, on top of the shared weights and biases. My naive approach was to keep the ASGD update rule (since, as I see it, it just updates the central parameters values to the local ones), but I am getting inconsistent values (duplicated sample indices) in the shared loss array after an epoch or so of training. I thought it could be related to the param sync rule, I'll just keep digging.

Again, thanks for your help!
