### ISSUE TITLE
posix_ipc

### ISSUE THREAD

**Issue by yaoli** [mila-udem/platoon#8]
Trying to understand why posix_ipc/shared memory is used. Can someone explain why in a bit more details? Thanks!

**Comment by yaoli** [comment]
And also the idea behind cffi?

**Comment by mgermain** [comment]
I think @abergeron is the one who made those design choice. He is probably the best suited to answer your questions.

**Comment by abergeron** [comment]
Shared memory is used so that communication costs are as low as possible between workers/soldiers.  The simplest way to use that was posix_ipc so in the interest of time I chose to use that module.

As for cffi, I don't really care about it.  All I want is a way to mmap some file into a python read/write buffer, which is apparently something that is impossible with the base modules (including ctypes).  So I turned to cffi because it has the functionality to turn a arbitrary pointer into a python buffer.

I could also have written my own C python extension, but that would have taken longer to debug and make work.

**Comment by yaoli** [comment]
Hmm, I see a little better. Just trying to understand the design of this new kid. 

How is cffi related to posix_ipc? With ZMQ, masters and workers could just directly pass parameters through sockets, and is there extra reason of why posix_ipc + cffi combo is used?

**Comment by abergeron** [comment]
Passing parameters through sockets would be much slower.  That is the whole reason.

**Comment by dwf** [comment]
Even with the Unix IPC socket type? http://api.zeromq.org/2-1:zmq-ipc (I
imagine you're right about loop back TCP sockets.)

A possible advantage to doing it with IPC ZMQ sockets is that the same code
(modulo a protocol string) could be used on Windows with a slower TCP
fallback. But without a benchmark it's hard to say whether it'd be a speed
hit.

**Comment by bartvm** [comment]
ZMQ uses Unix domain sockets, which still requires copying; it bypasses network protocols like TCP, but it still copies data on a kernel level. Shared memory on the other hand requires zero copying. ZMQ has no support for shared memory, but we could look into [nanomsg](http://nanomsg.org/documentation-zeromq.html). From its documentation:

> While ZeroMQ offers a "zero-copy" API, it's not true zero-copy. Rather it's "zero-copy till the message gets to the kernel boundary". From that point on data is copied as with standard TCP. nanomsg, on the other hand, aims at supporting true zero-copy mechanisms such as RDMA (CPU bypass, direct memory-to-memory copying) and shmem (transfer of data between processes on the same box by using shared memory). The API entry points for zero-copy messaging are nn_allocmsg and nn_freemsg functions in combination with NN_MSG option passed to send/recv functions.

**Comment by nouiz** [comment]
@mgermain found elsewhere that nanomsg would fix another problem with zeromq. @mgermain we talked about 3 problems this morning, which one it was fixing?

note: nanomsg work on windows.

**Comment by mgermain** [comment]
The nanomsg doc says:
> REQ socket in ZeroMQ cannot be really used in real-world environments, as they get stuck if message is lost due to service failure or similar. Users have to use XREQ instead and implement the request re-trying themselves. With nanomsg, the re-try functionality is built into REQ socket.

http://nanomsg.org/documentation-zeromq.html

Not having to work around that would simplify the code a bit.

**Comment by nouiz** [comment]
And having only one mechanism for contral and data would be good too if it
don't loose speed. From the few information I have, I think it could be as
fast as the shared memory. If you have different expectation, tell it.

This won't be for this week for sure.

**Comment by abergeron** [comment]
Yes we can look into using nanomsg instead of zeroMQ which may simplify the code.

However more investigation has to be done to make sure that we can replicate the weight-sharing we currently do.  I'm not a 100% convinced it would work yet.

On the other hand even if we can't do it, as long as the speed is there, then I don't really care how it's done.

**Comment by nouiz** [comment]
We can see if we have time to investigate this more next week. This won't
speed it up and windows isn't a prio. The prio is to have people use it.
